function h5exportRaw(obj, file_name)

hdf5write(file_name, ...
         '/ptychogram', obj.ptychogram,... 
         '/encoder', obj.positions0*obj.dxo,...
         '/dxd', obj.dxd,...
         '/zo', obj.zo,...
         '/wavelength', obj.wavelength);

end
